apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "fullname" . }}
    labels:
        draft: {{ default "draft-app" .Values.draft }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
    {{ (.Files.Glob "classes/**.yml").AsConfig | nindent 2 }}



    {{- /* range $path, $bytes := .Files.Glob "classes/*.yml" }}
    {{ base $path }}: >- {{ .Files.Get $path }}
    {{ end */ -}}
